apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    compileSdkVersion rootProject.tools.compileSdk
    repositories {
        google()
        mavenCentral()
    }
    defaultConfig {
        minSdkVersion rootProject.tools.minSdk
        targetSdkVersion rootProject.tools.targetSdk
        versionCode 1
        versionName "${rootProject.tools.versionName}"
    }

}

dependencies {
    implementation 'androidx.core:core:1.7.0'
    api 'com.github.mhiew:pdfium-android:1.9.2'
}

allprojects {
    repositories {
        google()
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
    }
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.github.mhiew'
            artifactId = 'android-pdf-viewer'
            version = '3.0.0'

            afterEvaluate {
                from components.release
            }
        }
    }
}
